### ISSUE TITLE
[BUG]  Examples not included in MANIFEST.in

### ISSUE THREAD

**Issue by koning** [LLNL/merlin#101]
## 🐛 Bug Report

**Describe the bug**
An exception is given when running merlin with spack, or any install that relocates merlin.
```
[sh]: merlin
.
.
.
FileNotFoundError: [Errno 2] No such file or directory: '<path>/site-packages/merlin/examples/workflows'
```

**To Reproduce**
Install merlin with spack, type merlin

**Expected behavior**
No exceptions.

**Comment by ben-bay** [comment]
Fixing now, just adding `include merlin/examples/workflows/*`. Does that look right?

**Comment by koning** [comment]
No, I believe it is relative to the top level so no merlin/. Look at the other directories in that file.

**Comment by koning** [comment]
Actually I take that back, that is correct with the merlin/
