### ISSUE TITLE
[FEAT] merlin block errors and outputs

### ISSUE THREAD

**Issue by ymubarka** [LLNL/merlin#117]
## 🚀 Feature Request

**What problem is this feature looking to solve?**
When I try to generate samples from the merlin block I don't get an error telling me what went wrong. It gives an error that is unrelated to the actual bug which is in the script itself. That error is suppressed when it should be outputted somewhere.

**Describe the solution you'd like**
Printing the error just like in the study block and having an out and err files.

**Describe alternatives you've considered**
Manually going every step and trying to figure out what went wrong. This takes way too long and it's not always clear where the problem is unless everything is broken down.

**Comment by ben-bay** [comment]
@lucpeterson if I add a place for the stdout and stderr of the samples, do you think `merlin_info/` would be a good spot?

**Comment by ben-bay** [comment]
Added with #234
