### ISSUE TITLE
[FEAT] alternate samples shell

### ISSUE THREAD

**Issue by ben-bay** [LLNL/merlin#132]
## 🚀 Feature Request

**What problem is this feature looking to solve?**
To provide a solution for times when sample generation could be done with a small python script instead of a bash call to an external script.

**Describe the solution you'd like**
Add an optional `merlin.samples.generate.shell` entry, same as `<step>.run.shell`.

**Comment by AlexanderWinterLLNL** [comment]
This may be something to revisit after [this ticket for one-off/shell scripts is done](https://github.com/LLNL/merlin/issues/208).
