### ISSUE TITLE
[FEAT]  Speed up task creation

### ISSUE THREAD

**Issue by lucpeterson** [LLNL/merlin#166]
## 🚀 Feature Request

**What problem is this feature looking to solve?**
This is a bottleneck on large-scale task recreation (500 secs to create 100k) and could be parallelized with additional tasks.

**Describe the solution you'd like**
Break up the lists etc into groups of tasks to make it parallel.

**Describe alternatives you've considered**
Use something like asyncio, but we're already using celery so we should just do this.

**Additional context**
We may have to break up the functions as we dig down.

**Comment by lucpeterson** [comment]
https://github.com/LLNL/merlin/blob/a0cce1cf7921bc98a504433709826c5d93941071/merlin/common/tasks.py#L218

**Comment by ben-bay** [comment]
#177

**Comment by ben-bay** [comment]
Fixed in #195
