### ISSUE TITLE
[FEAT] zfill sample paths

### ISSUE THREAD

**Issue by lucpeterson** [LLNL/merlin#173]
## 🚀 Feature Request

**What problem is this feature looking to solve?**
The sample path files 0/0/0 etc end up not being in order

**Describe the solution you'd like**
zfill the samples directories, so that you get 00/00/00 etc

**Describe alternatives you've considered**
do nothing

**Additional context**
we'll have to make sure we catch everywhere the directories are written

**Comment by ben-bay** [comment]
Added in #176
