### ISSUE TITLE
[BUG] merlin info should generate key

### ISSUE THREAD

**Issue by ben-bay** [LLNL/merlin#189]
## 🐛 Bug Report

**Describe the bug**
Even with the proper results backend password in `app.yaml`, a run of `merlin info` shows the results backend as not working because `encrypt_data_key` has not yet been generated.

**To Reproduce**
1. Remove `encrypt_data_key` from merlin home dir. 
2. Run `merlin info`
3. See authentication error

**Expected behavior**
`merlin info` should generate its own `encrypt_data_key` if one does not yet exist.

**Comment by koning** [comment]
I do not see an authentication error when I remove the key.

**Comment by ben-bay** [comment]
You're right, this behavior isn't as clear-cut as I originally thought.

**Comment by koning** [comment]
I think we should add encryption.init_key() to the celery config creation step.
