### ISSUE TITLE
[BUG] run-workers --echo sends logs wrong message

### ISSUE THREAD

**Issue by ben-bay** [LLNL/merlin#190]
## 🐛 Bug Report

**Describe the bug**
`run-workers --echo` shows the logger message: 
```
[2020-03-23 16:23:18: INFO] Launching workers from <spec.yaml>'
```

**Expected behavior**
No incorrect logger message.

**Comment by koning** [comment]
Are you objecting to the <spec.yaml> placeholder?

**Comment by ben-bay** [comment]
No, that's a placeholder I added. I mean that `run-workers --echo` doesn't actually run any workers, so there shouldn't be a logger message saying workers are being launched.
