### ISSUE TITLE
[BUG] MERLIN_RESTART overwriting the .out and .err files

### ISSUE THREAD

**Issue by ymubarka** [LLNL/merlin#197]
## 🐛 Bug Report

When exiting with a `$(MERLIN_RESTART)` flag, merlin overwrites the `.out` and `.err` files with the restart steps' own `.out` and `.err` files as opposed to creating new outputs files specifically for the restart step like with the .sh files

**To Reproduce**

**Expected behavior**
The expected outputs should be something like this:
`step.err
step.out
step.sh
step.restart.err
step.restart.out
step.restart.sh`

but it's only outputting:

`step.err
step.out
step.sh
step.restart.sh`

**Comment by koning** [comment]
This issue is actually a feature of maestro. It uses the step name instead of the step.restart name for the output files. Fixed in #199.

**Comment by ben-bay** [comment]
Fixed in #199
