### ISSUE TITLE
[BUG] Rogue string expansion

### ISSUE THREAD

**Issue by ben-bay** [LLNL/merlin#201]
## 🐛 Bug Report

**Describe the bug**
The string "$_" expands to a path in the venv.

**To Reproduce**
1. Add "$_" anywhere in a spec
2. `merlin run <spec.yaml>`
3. Look in the provenance file.

**Expected behavior**
The string "$_" should not change.

EDIT: According to [this](https://stackoverflow.com/questions/5163144/what-are-the-special-dollar-sign-shell-variables), "$_" is a special shell variable.

**Comment by lucpeterson** [comment]
I think we need to remove the expanduser and expandvars references by Merlin outside of the workers

https://github.com/LLNL/merlin/blob/54166e0920eb2aac36ba9fbd524ddd9680b2b1d1/merlin/spec/expansion.py#L83

I propose we leave user and environment variables alone and let the workers take care of them as they would at run time

**Comment by ben-bay** [comment]
@lucpeterson okay, so even symbols like `~` won't work then

**Comment by lucpeterson** [comment]
we should check whether having "~" in a spec file would work or not

**Comment by lucpeterson** [comment]
i bring this up to address Timo's desire to use environment variables in spec descriptions for extra flexibility

**Comment by ben-bay** [comment]
I see, good point. It's an easy fix, I'll run some tests to make sure what we think is happening is happening.

**Comment by ben-bay** [comment]
Ohhhh I see the problem. Has nothing to do with `$`. We should leave env vars alone, to instead be interpreted by each step's shell and not meddled with by merlin.

**Comment by ben-bay** [comment]
#247

**Comment by koning** [comment]
To be clear, you should be able to use env variables in all sections except the steps. These are definitely used in the batch section.

**Comment by lucpeterson** [comment]
Do we have to explicitly replace them or can they be replaced by the native shell? Can we center around an example?

**Comment by koning** [comment]
Well the point is to replace them immediately, like paths to flux in the batch section. There are not part of a step so they won't be replaced by the env when they are run. Also in variables in the env section, those should be replaced at run, if a user wants the variable to remain unchanged , it should be in a step.

**Comment by koning** [comment]
I think this is semantics, by replaced I mean made available at run with the run env variables. So yes, as long as they are in the shell when run it is fine.

**Comment by lucpeterson** [comment]
Ah ok, I think leaving them alone (and exposed) at run time will actually fix another (related) bug/feature. I was having issues using ${SYS_TYPE} in the batch section for flux w/ run-workers and was having a hard time tracking it down. Not sure yet if it's related, but there was some odd behavior

**Comment by ben-bay** [comment]
Fixed with #247
