### ISSUE TITLE
[FEAT] Relax requirement for different machines

### ISSUE THREAD

**Issue by lucpeterson** [LLNL/merlin#207]
## 🚀 Feature Request

**What problem is this feature looking to solve?**
Currently multi-machine workflows need to be able to both have access to the same workspace on the file system. This can be pretty limiting. For instance, running a multi-machine workflow on two machines with different air-gapped parallel file systems would require the workspaces to be in a common location, ie not on the parallel file systems. The user would have to do gymnastics to make the tasks run on the parallel file systems, but have a workspace in a shared spot.

**Describe the solution you'd like**
The ability to do this. Possible solutions/paths forward
- allow for a step-wise defined overwrite of the workspace location, maybe allowing "None"
- delay the instantiation of the DAG/sample generation as a task to be executed by a worker (so that `merlin run` can launch work to be done elsewhere)

Issues to consider
- the MERLIN_FINISHED files -- shouldn't we move these to a database or file or something?
- how to record where the workspaces are? (broken) symlinks? a file?

**Comment by ben-bay** [comment]
@lucpeterson in your mind, what does "None" signify, as a step's workspace location?

**Comment by AlexanderWinterLLNL** [comment]
This should be revisited [after this ticket is completed](https://github.com/LLNL/merlin/issues/238) as there may be interdependency/overlap with the centralized logging. Especially around where log files are routed/stored across the different machines.
