### ISSUE TITLE
[BUG] Duplicated cryptography install

### ISSUE THREAD

**Issue by lucpeterson** [LLNL/merlin#21]
**Describe the bug**
Cryptography is in the makefile (installed with easy_install) and in the requirements.txt. The easy_install was a temporary workaround that should be removed. Having it in both places means the pip install ignores cryptography.

**Expected behavior**
No dependency installs in makefile: everything should be in requirements.

**Comment by ben-bay** [comment]
I agree that a lot of material in the Makefile is ready to be removed.

**Comment by ben-bay** [comment]
#43

**Comment by ben-bay** [comment]
Resolved with PR #49
