### ISSUE TITLE
[FEATURE] Check version increments on master PRs

### ISSUE THREAD

**Issue by lucpeterson** [LLNL/merlin#22]
**Is your feature request related to a problem? Please describe.**
We want to keep the CHANGELOG and version updated as master is changed.

**Describe the solution you'd like**
A travis check that the CHANGELOG and version in merlin/__init__.py have been modified for every PR into master.

**Describe alternatives you've considered**
As an alternative, we could have a test that looks for changes and have people run it by hand or have travis run that test. I do think an automated alert that says "hey, this needs to be changed" would be helpful. Much like a style check.

**Comment by ben-bay** [comment]
Update: version checking is currently on `develop`. Still needs to undergo some testing.
