### ISSUE TITLE
[FEATURE] Improve visibility timeout

### ISSUE THREAD

**Issue by lucpeterson** [LLNL/merlin#222]
https://github.com/LLNL/merlin/blob/2f726c6c4aa61fce405617ff3cb2420f4cb0aa26/merlin/celery.py#L105

Right now, this is defaulted to 2 hours (despite the docs saying 1 hour). This is too short: apps that run longer than 2 hours could be run again by a new worker. This should be changed to 24 hours and we should expose it in the config file.

**Comment by ben-bay** [comment]
Addressed in #224
