### ISSUE TITLE
[BUG] Celery v4.4.3 breaks merlin

### ISSUE THREAD

**Issue by ben-bay** [LLNL/merlin#225]
## 🐛 Bug Report

Merlin breaks when attempting to use Celery version 4.4.3.

We have locked merlin at using Celery v4.4.2 to temporarily get around this, but we need a solution that allows us to use future versions of Celery.

**Comment by koning** [comment]
This issue persists in v4.4.4.

**Comment by ben-bay** [comment]
Same for 4.4.5
