### ISSUE TITLE
[BUG] Missing dependencies on pypi install

### ISSUE THREAD

**Issue by lucpeterson** [LLNL/merlin#23]
**Describe the bug**
pip install from pypi doesn't grab all the necessary dependencies

**To reproduce**
1. python3 -m virtualenv "testy"
2. source testy/bin/activate
3. pip install merlinwf
4. merlin
 -> breaks
"ModuleNotFoundError: No module named 'tabulate'"
5. pip install tabulate
6. merlin
 -> breaks
ModuleNotFoundError: No module named 'maestrowf'
7. pip install -e git+https://github.com/LLNL/maestrowf.git#egg=maestrowf
8. merlin
 -> success

**Expected behavior**
pip install merlinwf should grab all dependencies

**Comment by lucpeterson** [comment]
#31

**Comment by ben-bay** [comment]
`tabulate` has been added to `release.txt` on develop, and will be fixed in the next upload to PyPI. `maestrowf`, however, remains a problem.

**Comment by koning** [comment]
maestrowf fixed with #42

**Comment by ben-bay** [comment]
> maestrowf fixed with #42

...or so we thought. PyPI isn't allowing URL installs, so for now we wait until Maestro on PyPI gets `load_specification_from_stream` in v1.1.5, which Frank says whould come later today.
