### ISSUE TITLE
[FEATURE] Query tasks in the task broker queue?

### ISSUE THREAD

**Issue by srcopela** [LLNL/merlin#25]
Is there a way to query the remaining tasks on the task broker?  The merlin query-workers command is a bit too coarse to get a sense for the status of a currently running ensemble.

Probably more useful than a list of remaining tasks would be statistics on the total number of tasks in each queue, the number completed successfully, number failed, and number remaining.

**Comment by lucpeterson** [comment]
This is on the docket for the next big feature. The challenge is that current tools are very sever-specific (eg they interface directly with your rabbit server, and will only work if you have admin access). We are thinking of ways to enable some kind of "monitoring" without losing generality.

Right now I'm thinking this could be accomplished with a few tools:

- A "local" database/record of all the tasks associated with a study
- Code that registers your tasks with that database when they are launched
- A tool that gathers the results of those tasks from your backend (eg redis) server database, and copies them over locally
- A tool that can do analysis on the local database

There are a few challenges with querying the server database directly:

1. The database has everything in it, including tasks from different studies.
2. The values in that database are stored by task uuid (which isn't really useful for users, who really want to know how a particular step [ie directory workspace] did)
3. The database might not be persistent, unless set up by the users as such.



The idea is that periodically one could update a database stored in the $(MERLIN_INFO) directory which has the results of the tasks associated with that $(MERLIN_INFO) study. This database would be persistent and could be queried quickly for things like timestamp, directory, exit stats.

Totally open to suggestions. This is a big request that we've been brainstorming ways to deal with.

**Comment by AlexanderWinterLLNL** [comment]
This will be resolved by/duplicates issues touched on by [this ticket](https://github.com/LLNL/merlin/issues/238).
