### ISSUE TITLE
[BUG] Hello example fails

### ISSUE THREAD

**Issue by balazsfabian** [LLNL/merlin#262]
## 🐛 Bug Report

**Describe the bug**
The 'hello' example fails.

**To Reproduce**
1. `> merlin example hello`
2. `> cd hello`
3. `> merlin run --local hello.yaml`
4. `[2020-08-04 12:41:53: ERROR] 'NoneType' object is not iterable`

**Expected behavior**
The expected behavior is to run the example in the [tutorial](https://merlin.readthedocs.io/en/latest/modules/hello_world/hello_world.html)

**Please answer these questions to help us pinpoint the problem**
- Does the problem occur in `merlin run --local` mode, distributed mode or neither?
  local and distributed
- On what machines/architectures are you running merlin? Is this bug on a specific machine or can you reproduce it elsewhere?
 archlinux desktop, have not tried reproducing

**Please run `merlin info` and paste the results here:**
```[2020-08-04 13:07:50: INFO] Reading app config from file /home/balazs/.merlin/app.yaml
  
                                                
       *      
   *~~~~~                                       
  *~~*~~~*      __  __           _ _       
 /   ~~~~~     |  \/  |         | (_)      
     ~~~~~     | \  / | ___ _ __| |_ _ __  
    ~~~~~*     | |\/| |/ _ \ '__| | | '_ \ 
   *~~~~~~~    | |  | |  __/ |  | | | | | |
  ~~~~~~~~~~   |_|  |_|\___|_|  |_|_|_| |_|
 *~~~~~~~~~~~                                    
   ~~~*~~~*    Machine Learning for HPC Workflows                                 
              


Merlin Configuration
-------------------------

 config_file        | /home/balazs/.merlin/app.yaml
 is_debug           | False
 merlin_home        | /home/balazs/.merlin
 merlin_home_exists | True
 broker server      | redis://localhost:6379/0
 broker ssl         | False
 results server     | redis://localhost:6379/0
 results ssl        | False

Checking server connections:
----------------------------
broker server connection: OK
results server connection: OK

Python Configuration
-------------------------

 $ which python3
/home/balazs/Documents/Programs/merlin_env/bin/python3

 $ python3 --version
Python 3.7.6

 $ which pip3
/home/balazs/Documents/Programs/merlin_env/bin/pip3

 $ pip3 --version
pip 20.2.1 from /home/balazs/Documents/Programs/merlin_env/lib/python3.7/site-packages/pip (python 3.7)

"echo $PYTHONPATH"
```

**Additional context**
Maestro was able to run hello.yaml _provided_ that the shell was changed to the default, and the `print`
was also turned into an `echo`.

**Comment by ben-bay** [comment]
Fixed in 1.7.3
