### ISSUE TITLE
[BUG]  Openfoam_wf example fails

### ISSUE THREAD

**Issue by balazsfabian** [LLNL/merlin#263]
## 🐛 Bug Report

**Describe the bug**
The `openfoam_wf` example fails

**To Reproduce**
1. `merlin example openfoam_wf`
2. `cd openfoam_wf`
3. `merlin run --local openfoam_wf_template.yaml`
4. `[2020-08-04 16:36:42: ERROR] 'NoneType' object has no attribute 'items'`

**Expected behavior**
The expected behavior is to run the example in the [tutorial](https://merlin.readthedocs.io/en/latest/modules/run_simulation/run_simulation.htmll)

**Please answer these questions to help us pinpoint the problem**
- Does the problem occur in `merlin run --local` mode, distributed mode or neither?
  local and distributed
- On what machines/architectures are you running merlin? Is this bug on a specific machine or can you reproduce it elsewhere?
  archlinux desktop, have not tried reproducing

**Please run `merlin info` and paste the results here:**
```[2020-08-04 16:40:03: INFO] Reading app config from file /home/balazs/.merlin/app.yaml
  
                                                
       *      
   *~~~~~                                       
  *~~*~~~*      __  __           _ _       
 /   ~~~~~     |  \/  |         | (_)      
     ~~~~~     | \  / | ___ _ __| |_ _ __  
    ~~~~~*     | |\/| |/ _ \ '__| | | '_ \ 
   *~~~~~~~    | |  | |  __/ |  | | | | | |
  ~~~~~~~~~~   |_|  |_|\___|_|  |_|_|_| |_|
 *~~~~~~~~~~~                                    
   ~~~*~~~*    Machine Learning for HPC Workflows                                 
              


Merlin Configuration
-------------------------

 config_file        | /home/balazs/.merlin/app.yaml
 is_debug           | False
 merlin_home        | /home/balazs/.merlin
 merlin_home_exists | True
 broker server      | redis://localhost:6379/0
 broker ssl         | False
 results server     | redis://localhost:6379/0
 results ssl        | False

Checking server connections:
----------------------------
broker server connection: OK
results server connection: OK

Python Configuration
-------------------------

 $ which python3
/home/balazs/.conda/envs/mdanalysis/bin/python3

 $ python3 --version
Python 3.8.3

 $ which pip3
/home/balazs/.conda/envs/mdanalysis/bin/pip3

 $ pip3 --version
pip 20.1.1 from /usr/lib/python3.8/site-packages/pip (python 3.8)

"echo $PYTHONPATH"
```

**Additional context**
The `merlin_info` directory was generated along with `*.expanded.yaml`, `*.orig.yaml` and `*.partial.yaml`

**Comment by ben-bay** [comment]
Thank you for this, merlin 1.7.0 and 1.7.1 were unstable, but as of 1.7.3 we're more confident in our bugfixes. Does the 1.7.3 release function better for you?

**Comment by balazsfabian** [comment]
Thanks! merlin 1.7.3 solves the issue.
