### ISSUE TITLE
[BUG] merlin run does not support the -o flag

### ISSUE THREAD

**Issue by balazsfabian** [LLNL/merlin#268]
## 🐛 Bug Report

**Describe the bug**
As stated in in the [documentation](https://merlin.readthedocs.io/en/latest/merlin_specification.html), the
user can specify the output path to avoid timestamping. However, the `-o` flag is not supported by `merlin run`

**To Reproduce**
1. `merlin run --local hello.yaml -o test_dir`
2. `error: unrecognized arguments: -o test_dir`

**Expected behavior**
The expected behavior is to use `test_dir` as output directory.

**Please answer these questions to help us pinpoint the problem**
- Does the problem occur in `merlin run --local` mode, distributed mode or neither?
  local
- On what machines/architectures are you running merlin? Is this bug on a specific machine or can you reproduce it elsewhere?
  archlinux desktop, have not tried reproducing

**Please run `merlin info` and paste the results here:**
```[2020-08-05 11:54:53: INFO] Reading app config from file /home/balazs/.merlin/app.yaml
  
                                                
       *      
   *~~~~~                                       
  *~~*~~~*      __  __           _ _       
 /   ~~~~~     |  \/  |         | (_)      
     ~~~~~     | \  / | ___ _ __| |_ _ __  
    ~~~~~*     | |\/| |/ _ \ '__| | | '_ \ 
   *~~~~~~~    | |  | |  __/ |  | | | | | |
  ~~~~~~~~~~   |_|  |_|\___|_|  |_|_|_| |_|
 *~~~~~~~~~~~                                    
   ~~~*~~~*    Machine Learning for HPC Workflows                                 
              


Merlin Configuration
-------------------------

 config_file        | /home/balazs/.merlin/app.yaml
 is_debug           | False
 merlin_home        | /home/balazs/.merlin
 merlin_home_exists | True
 broker server      | redis://localhost:6379/0
 broker ssl         | False
 results server     | redis://localhost:6379/0
 results ssl        | False

Checking server connections:
----------------------------
broker server connection: Error
results server connection: Error

Exceptions:
broker server: Error 111 connecting to localhost:6379. Connection refused.
results server: Error 111 connecting to localhost:6379. Connection refused.

Python Configuration
-------------------------

 $ which python3
/home/balazs/.conda/envs/mdanalysis/bin/python3

 $ python3 --version
Python 3.8.3

 $ which pip3
/home/balazs/.conda/envs/mdanalysis/bin/pip3

 $ pip3 --version
pip 20.1.1 from /usr/lib/python3.8/site-packages/pip (python 3.8)

"echo $PYTHONPATH"
```

**Additional context**
`merlin --version` is `1.7.3`. (This really should be included in the [BUG] template, maybe even `merlin info`)

**Comment by ben-bay** [comment]
Thank you, really good catch. This looks like a case of us being lazy and copying Maestro's documentation, then failing to modify it for merlin. While don't support this `-o` flag, we do allow users to override variables with `merlin run ... --vars OUTPUT_PATH=custom/path`. Will this accomodate your need?

**Comment by balazsfabian** [comment]
Thank you! `merlin run ... --vars OUTPUT_PATH=custom/path` is indeed a viable alternative, only that the timestamped `$(MERLIN_WORKSPACE)` will still appear as a subdirectory. It is not an important detail, I just wondered if it was possible to omit the timestamp.

**Comment by ben-bay** [comment]
I see. We don't support this option yet, but it would be easy to add!
