### ISSUE TITLE
[FEATURE] Convenient signal from HPC applications to identify hard/soft fail conditions

### ISSUE THREAD

**Issue by srcopela** [LLNL/merlin#27]
Merlin has a way of registering success and failure of tasks through the the MERLIN_SOFT_FAIL and MERLIN_HARD_FAIL variables.  Each HPC application with terminate (successfully or otherwise) differently - is there a common protocol you want to suggest to application developers to triggering hard/soft fail conditions (e.g. write a file of a particular name, print to terminal, return an integer value)?

**Comment by lucpeterson** [comment]
I'm not quite sure I understand the request. Is there functionality you'd like beyond the 
`exit $(MERLIN_HARD_FAIL)` or `exit $(MERLIN_SOFT_FAIL)` handling?

**Comment by koning** [comment]
The system replaces those values in the yaml file directly, so they are subject to change. A typical code would be called from the task description which is eventually run as a shell script (this is up to the user).  

The method we currently use in the task/shell script is:
run simulation code
determine success/ fail of application
if success:
  exit $(MERLIN_SUCCESS)
else:
  exit $(MERLIN_SOFT_FAIL)
