### ISSUE TITLE
[FEAT] unify walltime syntax

### ISSUE THREAD

**Issue by lucpeterson** [LLNL/merlin#275]
## 🚀 Feature Request

**What problem is this feature looking to solve?**
The different script adapters require different syntax for the wall time entry. If the time directive is in the wrong format, Merlin will fail to write the $(LAUNCHER) command, but with a mysterious error.

**Describe the solution you'd like**
We should have a unified interface and error catching if the entry is ill-formatted.

**Describe alternatives you've considered**
Leave it as is and let users figure it out.

**Comment by koning** [comment]
There is only one time format that merlin accepts, the script adapters change it to the proper format.
