### ISSUE TITLE
[FEAT] merlin monitor for partially-completed workflows

### ISSUE THREAD

**Issue by ben-bay** [LLNL/merlin#278]
## 🚀 Feature Request

**What problem is this feature looking to solve?**
`merlin monitor` functionality for workflow error conditions, not just successful workflow completion. First mentioned in issue #277 

**Describe the solution you'd like**
New `merlin monitor` functionality that checks for the case where there are tasks in the queue, and the workers are not running any tasks, and have run tasks recently (error condition).

**Comment by AlexanderWinterLLNL** [comment]
This seems [related to this issue](https://github.com/LLNL/merlin/issues/238), we're possibly duplicating between the two.
