### ISSUE TITLE
[BUG] Transfer README material to web docs

### ISSUE THREAD

**Issue by ben-bay** [LLNL/merlin#28]
**Describe the bug**
Instead of continuing to support a large README file, move the bulk of it to readthedocs.

In the Spack repo, for example, the README is more manageable and concise.

**Comment by lucpeterson** [comment]
I agree that a lot of the stuff after the introduction should be moved to elsewhere in the docs. The README should have

1. an intro/overview
2. a user-focused quick start which has an installation guide and how to create and run one of the templates
