### ISSUE TITLE
[BUG] openfoam_wf fails on the combine_output step

### ISSUE THREAD

**Issue by papajim** [LLNL/merlin#303]
## 🐛 Bug Report

**Describe the bug**
The openfoam_wf fails on the combine_output step and subsequently on the learn step as well.

**To Reproduce**
1. docker pull cfdengine/openfoam
2. merlin example openfoam_wf
2. cd openfoam_wf
3. merlin run openfoam_wf_template.yaml
4. See error in combine_outputs.err

''' U = np.array(U).reshape(len(dir_names), num_of_timesteps, resolution, 3)
ValueError: cannot reshape array of size 6451200 into shape (100,10,400,3)
''''

**Expected behavior**
The openfoam_wf should finish successfully  with no errors.

**Screenshots**

**Please answer these questions to help us pinpoint the problem**
- Does the problem occur in `merlin run --local` mode, distributed mode or neither?
- If a distributed problem, which backend and queue servers are you using? How are they configured?
- On what machines/architectures are you running merlin? Is this bug on a specific machine or can you reproduce it elsewhere?

**Please run `merlin info` and paste the results here:**

**Additional context**

**Comment by lucpeterson** [comment]
@ymubarka can you take a look at this?

**Comment by ymubarka** [comment]
@papajim I just got the same issue when running with a higher concurrency than the number of cores I had. The issue here is that some docker containers are getting the same name. Try setting the concurrency for `simworkers` to be the same as the of cores on your cpu

**Comment by ben-bay** [comment]
@ymubarka is this now fixed?
