### ISSUE TITLE
[FEAT] Add verification for YAML specs

### ISSUE THREAD

**Issue by ben-bay** [LLNL/merlin#318]
## 🚀 Feature Request

When defining a workflow, indentation slip ups and typos can really mess up a yaml spec. Worse, this type of error can be difficult to trace because it is often caught somewhere deep in the code instead of at the beginning.

`jsonschema` can go a long way in verifying workflow specifications. It can deal with stuff like types, required/optional properties, string lengths, and unique items in lists. We added this to Maestro a while back but the feature never bubbled up to Merlin because of the Maestro/Merlin incompatibility. [This](https://github.com/LLNL/maestrowf/pull/243) was the first merged PR for spec verification, and a few more bugfixes by me followed, especially [this one](https://github.com/LLNL/maestrowf/pull/279).

We should add this to Merlin to help new users understand what's going on.

**Comment by bgunnar5** [comment]
@lucpeterson @koning I think this issue can be closed now that the maestro compatibility branch is merged

**Comment by lucpeterson** [comment]
address in #388
