### ISSUE TITLE
[BUG] requirements files not in source tarball

### ISSUE THREAD

**Issue by koning** [LLNL/merlin#32]
The requirements/* files are not in the source code tarball on pypi. These are required to use setup.py to install and should be included in the deployment.

**Comment by koning** [comment]
See #33

**Comment by ben-bay** [comment]
> The requirements/* files are not in the source code tarball on pypi. These are required to use setup.py to install and should be included in the deployment.

Is the solution to this problem the `MANIFEST.in` file you created?

**Comment by koning** [comment]
Yes, that is the fix.

**Comment by koning** [comment]
Fix is merged #33
