### ISSUE TITLE
[BUG] We are missing Changlelog info for 1.0.1 and 1.0.2 @ben-bay

### ISSUE THREAD

**Issue by lucpeterson** [LLNL/merlin#34]
We are missing Changlelog info for 1.0.1 and 1.0.2 @ben-bay

_Originally posted by @koning in https://github.com/LLNL/merlin/pull/33#issuecomment-561847719_

**Comment by ben-bay** [comment]
Yeah sorry, this was me trying to fix the Merlin logo on PyPI (still unsuccessful). PyPI forces us to use versioning by disallowing any duplicate tarball name, which forces us to increment the version on each upload.

I'll add something like: "Negligible" for updates like this.

**Comment by ben-bay** [comment]
Merged into develop in PR #38
