### ISSUE TITLE
[BUG] merlin example list gives an error

### ISSUE THREAD

**Issue by koning** [LLNL/merlin#347]
## 🐛 Bug Report

**Describe the bug**
Installed merlin in a python3.8.2 virtual env and ran:
merlin example info
Received an error instead of the list

**To Reproduce**
1. python3-3.8.2 -m venv py3.8 --system-site-packages
2. source py3.8/bin/activate
3. pip install merlin
4. merlin example list

**Expected behavior**
A print out of the example list

This is what I received
(py3.8) [machine]:merlin example list
[2021-10-27 16:03:19: ERROR] while scanning for the next token
found character '%' that cannot start any token
  in "<path>/venv/py3.8/lib/python3.8/site-packages/merlin/examples/workflows/optimization/template_optimization.yaml", line 189, column 6

**Comment by lucpeterson** [comment]
Fixed with #348
