### ISSUE TITLE
Add what is the default concurrency value to the documentation

### ISSUE THREAD

**Issue by kustowski1** [LLNL/merlin#410]
## Bug Report

**Describe the bug**
I was asked to put a request to add the default concurrency value to the documentation as a bug report.

**Additional context**
The documentation should mention that the default concurrency is the number of CPUs on the system: https://docs.celeryq.dev/en/latest/reference/cli.html#cmdoption-celery-worker-c

**Comment by koning** [comment]
The default concurrency is the total number of PUs available on the node, e.g. 72 for a 36 core CPU with 2 hardware threads.

**Comment by bgunnar5** [comment]
This was added in the v1.12.0 release when the documentation was overhauled to mkdocs
