### ISSUE TITLE
[FEATURE] Add periodic tasks

### ISSUE THREAD

**Issue by ben-bay** [LLNL/merlin#57]
**Describe the solution you'd like**
Tasks / steps defined in a spec that repeat every n seconds.

These would be able to depend on other steps, but would not be valid as a dependency for any other step.

**Comment by AlexanderWinterLLNL** [comment]
Should be revisted either after [this ticket](https://github.com/LLNL/merlin/issues/132) or the refactor that decouples Maestro from the Merlin internals (possibly after both).
