### ISSUE TITLE
[FEATURE] Batch script feature

### ISSUE THREAD

**Issue by ben-bay** [LLNL/merlin#61]
**Describe the solution you'd like**
`merlin run` flag `--batch` that interfaces with popular batch managers like Slurm, LSF, and Flux.

**Comment by koning** [comment]
Is there more detail for this feature request? Is this to override the batch type keyword?

**Comment by ben-bay** [comment]
I'm not exactly sure what the specifics will be in this feature. We can discuss it here. Just that we want Merlin to have the ability to take care of scheduling commands for the user. (Maybe like `$(LAUNCHER)` in Maestro.)

**Comment by koning** [comment]
$(LAUNCHER) is now implemented, is this issue now complete? If not, there needs to be more detail on what is being requested.

**Comment by ben-bay** [comment]
You're right, closing this issue for now.
