### ISSUE TITLE
[FEATURE] Handle maestrowf restart keyword

### ISSUE THREAD

**Issue by koning** [LLNL/merlin#74]
On the road to running a full meastrowf yaml spec is to implement a handler for the restart commands in a step. The issue with this keyword is that it may be necessary to restart the initial task as opposed to always running the restart cmd on task restart. Research must be done to determine if this is possible in the celery system.

A possible solution would be to split a parallel run task into multiple tasks including a setup task and then only have the parallel launch commands including initial and restart for a run step.

**Comment by koning** [comment]
This could possibly be handled by a specific Merlin exit code. In Maestro the restart is used if a job times out due to an allocation time limit, where in Merlin the task could fail for more reasons than just a timeout. In some cases the user would like to restart the initial command and in some other cases, the restart command so there needs to be a way to handle that distinction.  A special return code e.g. MERLIN_MAESTRO_RESTART could cause the task to call the restart script instead of the initial task command.

**Comment by lucpeterson** [comment]
I also gravitated towards a separate return code to handle this. Really we have "retry" (which executes the cmd block again) and "restart" (which executes the restart cmd block).

**Comment by koning** [comment]
Merged into develop.
